### ISSUE TITLE
Baseman with Coverage collectors

### ISSUE THREAD

**Issue by dploeger** [vilic/baseman#1]
I'd like to gather code coverage data when baseman is run. I tried to run baseman in my instrumented code, but that produced no coverage.

Is this something, baseman should be already supporting and I'm just doing something wrong here or is it lacking from baseman?

**Comment by vilic** [comment]
Hi, I am using `nyc` for `clime` x `baseman` tests. It is a wrapper for `istanbul` with support for applications that spawn subprocesses.

https://github.com/istanbuljs/nyc

But if spawning a process is not the case, I think you may try something like executing baseman entrance file (`bld/cli/index.js`) directly with the test runner.

**Comment by dploeger** [comment]
Ah, okay. I'll test that. Thanks.
